[book]
authors = ["Samer"]
language = "en"
src = "src"
title = "The Motoko Programming Language Book"

[output.html]
unsafe = true

additional-js = ["theme/motoko.js"]

git-repository-icon = "fa-github"
git-repository-url = "https://github.com/Web3NL/motoko-book"
edit-url-template = "https://github.com/Web3NL/motoko-book/edit/main/{path}"

default-theme = "ayu"
preferred-dark-theme = "ayu"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding

